### ISSUE TITLE
Provide health-check endpoint for Docker healh-check procedure

### ISSUE THREAD

**Issue by dgroup** [dgroup/g2w#56]
So far this option could be used:
```yml
    healthcheck:
      test: curl -f http://localhost:8080/openapi.json || exit 1
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
```

In future we may create more sophisticated endpoint with custom checks...
